import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
export default function Home() {
  return (
    <div className="bg-ingehack-black">
      <Head>
        <title>IngeHack 2k22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen">
        <Navbar />
        <Hero />
      </div>
    </div>
  )
}
